const keyMap = {
  // common
  postingAs: "iam",
  postAs: "postas",
  postFor: "postFor",
  name: "name",
  email: "email",
  mobile: "mobile",
  whatsapp: "whatsapp",
  for: "forr",
  type: "property_type",
  address: "address",
  city: "city",
  locality: "locality",
  nearByLocation1: "locality2",
  nearByLocation2: "locality3",
  nearByLocation3: "locality4",
  nearByLocation4: "locality5",
  latitude: "latitude",
  longitude: "longitude",
  // propertyDetails
  projectName: "project_name",
  landZone: "land_zone",
  idealForBusinesses: "ideal_business",
  nearbyBusinesses: "near_by",
  // propertyFeatures
  isRK: "isRK",
  bedrooms: "bedroom",
  bathrooms: "bathroom",
  balconies: "balconies",
  floorNo: "floor_no",
  totalFloors: "total_floor",
  furnishedStatus: "furnish_status",
  floorsAllowed: "floors_alloww",
  noOfOpenSides: "open_side",
  widthOfRoadFacing: "width_road",
  anyConstructionDone: "any_con",
  boundaryWallMade: "wall_made",
  isInAGatedColony: "colony",
  washrooms: "washrooms",
  personalWashroom: "per_washroom",
  pantryCafeteria: "pantry",
  willingToModifInteriors: "willing_to",
  lockinPeriod: "lockin",
  cornerShop: "corner_shop",
  isMainRoadFacing: "main_road",
  cornerShowroom: "corner_showroom",
  // area
  areaIn: "area_unit",
  superArea: "super_area",
  builtupArea: "built_area",
  carpetArea: "carpet_area",
  coveredArea: "covered_area",
  widthOfEntrance: "width_entrace",
  plotArea: "plot_area",
  plotLength: "plot_length",
  plotBreadth: "plot_breadth",
  isCornerPlot: "corner",
  community: "community",
  buildingType: "building_type",
  // transactionType
  transactionType: "transaction_type",
  possessionStatus: "prop_availability",
  availableFrom: "avai_from_year",
  ageOfConstruction: "age_of_con",
  // priceDetails
  expectedPrice: "exp_price",
  priceInWord: "price_words",
  pricePerSqft: "price_per",
  pricePerSqYrd: "price_per_sqyrd",
  otherCharges: "otc_chrg",
  stampDutyCharges: "registration_charge",
  bookingOrTokenAmount: "booking_amt",
  maintenanceCharge: "maintainance",
  maintenancePer: "per",
  monthlyRent: "monthly_rent",
  electricityCharges: "electricity_water",
  depositAmount: "security_amt",
  // carParking
  carParking: "car_parking",
  multiUnitAvai: "multi_unit",
  overlooking: "overlookng",
  // video
  youtubeLink: "youtubeLink",
  instagramLink: "instagramLink",
  // statusOfWaterAndElectricity
  availOfWater: "avail_water",
  statusOfElec: "electricity",
  ownershipStatus: "ownership_status",
  // plotApprovalAuthority
  plotApprovalAuthority: "appr_authority",
  approvedBy: "approved_by",
  // connectivity
  connectivity: "connectivity",
  within2km: "connectivity_within",
  within5km: "conn_within1",
  within10km: "conn_within2",
  // flooring
  flooring: "flooring",
  // amenities
  amenities: "amenities",
  // descriptionAndLandmarks
  interestingPropertyDetails: "int_prop_detail",
  landmarksAndNeighbourhood: "landmark_neigh",
};

const keyValues = {
  propertyType: {
    1: "Flat/Apartment",
    2: "Residential House",
    3: "Villa",
    4: "Builder Floor Apartment",
    5: "Residential Land/Plot",
    6: "Penthouse",
    7: "Studio Apartment",
    8: "Service Apartment",
    9: "Commercial Office Space",
    10: "Office in IT Park/SEZ",
    11: "Commercial Shop",
    12: "Commercial Showroom",
    13: "Commercial Land",
    14: "Warehouse/Godown",
    15: "Industrial Land",
    16: "Industrial Shed",
    17: "Industrial Building",
    18: "Agricultural Land",
    19: "Farm House",
  },
  constructionStatus: {
    1: "Ready To Move",
    2: "Under Construction",
  },
  /* postBy: {
    1: "Owner",
    2: "Builder",
    3: "Dealer",
  }, */
  furnishing: {
    1: "Furnished",
    2: "Semi-Furnished",
    3: "Unfurnished",
  },
  lookingFor: {
    1: "Ready Possession",
    2: "Possession in 1 Year",
    3: "Possession in 2 Years",
    4: "Possession in 3 Years",
  },
};

const imageTypes = [
  "Main Image",
  "Exterior View",
  "Living Room",
  "Bedrooms",
  "Bathrooms",
  "Kitchen",
  "Floor Plan",
  "Master Plan",
  "Location Map",
  "Others",
  "Site View",
  "Common Area",
  "Washrooms",
  "Videos",
  "Brochure",
];

const propertyCardFields = `
  p.property_type, 
  p.postFor, 
  p.iam, 
  p.project_name, 
  p.locality, 
  p.city, 
  p.exp_price, 
  p.monthly_rent, 
  p.isRK, 
  p.bedroom, 
  p.bathroom, 
  p.washrooms, 
  p.area_unit, 
  p.carpet_area, 
  p.super_area, 
  p.plot_length, 
  p.plot_breadth, 
  p.prop_availability, 
  p.ownership_status, 
  p.open_side, 
  p.status,
  p.isActive
`;

const step1FormFields = {
  "Flat/Apartment": {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "superArea",
      "builtupArea",
      "carpetArea",
      "community",
      "buildingType",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "superArea",
      "builtupArea",
      "carpetArea",
      "community",
      "buildingType",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Residential House": {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "community",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "community",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  Villa: {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "community",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "community",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Builder Floor Apartment": {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "community",
      "buildingType",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "community",
      "buildingType",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  Penthouse: {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "community",
      "buildingType",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "community",
      "buildingType",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Studio Apartment": {
    Sale: [
      "projectName",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "community",
      "buildingType",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "community",
      "buildingType",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Service Apartment": {
    "Rent/Lease": [
      "projectName",
      "postingAs",
      "bedrooms",
      "bathrooms",
      "balconies",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "carpetArea",
      "community",
      "buildingType",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Residential Land/Plot": {
    Sale: [
      "projectName",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "anyConstructionDone",
      "boundaryWallMade",
      "isInAGatedColony",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "transactionType",
      "expectedPrice",
      "priceInWord",
      "pricePerSqYrd",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
    ],
  },
  "Commercial Office Space": {
    Sale: [
      "projectName",
      "landZone",
      "idealForBusinesses",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "personalWashroom",
      "pantryCafeteria",
      "areaIn",
      "carpetArea",
      "coveredArea",
      "plotArea",
      "community",
      "buildingType",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "depositAmount",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "idealForBusinesses",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "personalWashroom",
      "pantryCafeteria",
      "lockinPeriod",
      "carpetArea",
      "coveredArea",
      "plotArea",
      "community",
      "buildingType",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Office in IT Park/SEZ": {
    Sale: [
      "projectName",
      "landZone",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "personalWashroom",
      "pantryCafeteria",
      "areaIn",
      "carpetArea",
      "plotArea",
      "coveredArea",
      "community",
      "buildingType",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "areaIn",
      "carpetArea",
      "coveredArea",
      "plotArea",
      "community",
      "buildingType",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Commercial Shop": {
    Sale: [
      "projectName",
      "landZone",
      "nearbyBusinesses",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "personalWashroom",
      "pantryCafeteria",
      "cornerShop",
      "isMainRoadFacing",
      "areaIn",
      "carpetArea",
      "plotArea",
      "coveredArea",
      "community",
      "buildingType",
      "widthOfEntrance",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "nearbyBusinesses",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "personalWashroom",
      "pantryCafeteria",
      "lockinPeriod",
      "cornerShop",
      "isMainRoadFacing",
      "areaIn",
      "carpetArea",
      "plotArea",
      "coveredArea",
      "community",
      "buildingType",
      "widthOfEntrance",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Commercial Showroom": {
    Sale: [
      "projectName",
      "landZone",
      "nearbyBusinesses",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "personalWashroom",
      "pantryCafeteria",
      "isMainRoadFacing",
      "cornerShowroom",
      "areaIn",
      "carpetArea",
      "plotArea",
      "coveredArea",
      "community",
      "buildingType",
      "widthOfEntrance",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "nearbyBusinesses",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "washrooms",
      "personalWashroom",
      "pantryCafeteria",
      "lockinPeriod",
      "cornerShop",
      "isMainRoadFacing",
      "areaIn",
      "carpetArea",
      "plotArea",
      "coveredArea",
      "community",
      "buildingType",
      "widthOfEntrance",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Commercial Land": {
    Sale: [
      "projectName",
      "landZone",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "boundaryWallMade",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "transactionType",
      "expectedPrice",
      "priceInWord",
      "pricePerSqYrd",
      "otherCharges",
      "bookingOrTokenAmount",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "monthlyRent",
      "otherCharges",
      "depositAmount",
    ],
  },
  "Warehouse/Godown": {
    Sale: [
      "projectName",
      "landZone",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "floorNo",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Industrial Land": {
    Sale: [
      "projectName",
      "landZone",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "anyConstructionDone",
      "boundaryWallMade",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "transactionType",
      "expectedPrice",
      "priceInWord",
      "pricePerSqYrd",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
    ],
  },
  "Industrial Building": {
    Sale: [
      "projectName",
      "landZone",
      "totalFloors",
      "areaIn",
      "coveredArea",
      "plotArea",
      "community",
      "buildingType",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "totalFloors",
      "areaIn",
      "coveredArea",
      "plotArea",
      "community",
      "buildingType",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Industrial Shed": {
    Sale: [
      "projectName",
      "landZone",
      "floorsAllowed",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "landZone",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
  "Agricultural Land": {
    Sale: [
      "projectName",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "boundaryWallMade",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "transactionType",
      "expectedPrice",
      "priceInWord",
      "pricePerSqYrd",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
    ],
    "Rent/Lease": [
      "projectName",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "boundaryWallMade",
      "areaIn",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "transactionType",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
    ],
  },
  "Farm House": {
    Sale: [
      "projectName",
      "bedrooms",
      "bathrooms",
      "totalFloors",
      "furnishedStatus",
      "noOfOpenSides",
      "widthOfRoadFacing",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "transactionType",
      "possessionStatus",
      "availableFrom",
      "ageOfConstruction",
      "expectedPrice",
      "priceInWord",
      "pricePerSqft",
      "otherCharges",
      "stampDutyCharges",
      "bookingOrTokenAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
    "Rent/Lease": [
      "projectName",
      "bedrooms",
      "bathrooms",
      "totalFloors",
      "furnishedStatus",
      "areaIn",
      "coveredArea",
      "plotArea",
      "plotLength",
      "plotBreadth",
      "isCornerPlot",
      "carpetArea",
      "availableFrom",
      "ageOfConstruction",
      "monthlyRent",
      "otherCharges",
      "electricityCharges",
      "depositAmount",
      "maintenanceCharge",
      "maintenancePer",
    ],
  },
};

const requirementFormData = {
  property_for: {
    key: "property_for",
    label: "For",
    options: ["Buy", "Rent/Lease"],
  },
  bedrooms: {
    key: "bedrooms",
    label: "Bedrooms",
    options: Array.from({ length: 10 }, (_, i) => i + 1),
  },
  lookingFor: {
    key: "lookingFor",
    label: "Looking For",
    options: [
      "Ready Possession",
      "Possession in 1 Year",
      "Possession in 2 Years",
      "Possession in 3 Years",
    ],
  },
  floor: {
    key: "floor",
    label: "Floor",
    options: ["0 - 5 Floor", "6 - 10 FLoor", "11 - 15 Floor", "Above 15"],
  },
  parking: {
    key: "parking",
    label: " Car Parking?",
    options: ["Not Required", "Open", "Covered", "Open + Covered"],
  },
  balcony: {
    key: "balcony",
    label: "Balcony Preference",
    options: ["Not Required", "Yes", "Maybe"],
  },
  community: {
    key: "community",
    label: "Community Preference",
    options: [
      "Not Required",
      "Hindu",
      "Christian",
      "Muslim",
      "Gujarati",
      "Punjabi",
      "Marwadi",
      "Cosmos",
    ],
  },
  furnish_status: {
    key: "furnish_status",
    label: "Furnished Status",
    options: ["Unfurnished", "Semi-furnished", "Furnished"],
  },
  meeting: {
    key: "meeting",
    label: "Meeting With",
    options: ["Alone", "With Family", "With Spouse"],
  },
  buildingType: {
    key: "buildingType",
    label: "Building Type",
    options: ["Standalone", "Complex", "Township"],
  },
  connectivity: {
    key: "connectivity",
    label: "Connectivity",
    options: ["Railway", "Airport", "Metro", "Road"],
  },
  within2km: {
    key: "within2km",
    label: "Connectivity Within 2 km",
    options: [
      "School",
      "College",
      "Hospital",
      "Malls",
      "Market",
      "Station",
      "Bank",
      "Bus Stop",
      "Temple",
    ],
  },
  within5km: {
    key: "within5km",
    label: "Connectivity Within 5 km",
    options: [
      "School",
      "College",
      "Hospital",
      "Malls",
      "Market",
      "Station",
      "Bank",
      "Bus Stop",
      "Temple",
    ],
  },
  within10km: {
    key: "within10km",
    label: "Connectivity Within 10 km",
    options: [
      "School",
      "College",
      "Hospital",
      "Malls",
      "Market",
      "Station",
      "Bank",
      "Bus Stop",
      "Temple",
    ],
  },
};

const propertyFormData = {
  projectName: {
    key: "projectName",
    type: "text",
    label: "Name of Project/Society",
    value: "",
  },
  postingAs: {
    key: "postingAs",
    type: "radio",
    label: "You are posting as",
    options: ["Full House", "On Sharing Basis"],
    value: "",
  },
  landZone: {
    key: "landZone",
    type: "select",
    label: "Land Zone",
    options: [
      "Industrial",
      "Commercial",
      "Residential",
      "Transport and Communication",
      "Public Utilities",
      "Public and Semi Public Use",
      "Open Spaces",
      "Agricultural Zone",
      "Special Economic Zone",
      "Natural Conservation Zone",
      "Government Use",
    ],
    value: "",
  },
  idealForBusinesses: {
    key: "idealForBusinesses",
    type: "text",
    label: "Ideal For Businesses",
    value: "",
  },
  nearbyBusinesses: {
    key: "nearbyBusinesses",
    type: "text",
    label: "Nearby Businesses",
    value: "",
  },
  bedrooms: {
    key: "bedrooms",
    type: "btnSingle",
    label: "Bedrooms",
    options: Array.from({ length: 10 }, (_, i) => i + 1),
    value: "",
  },
  bathrooms: {
    key: "bathrooms",
    type: "btnSingle",
    label: "Bathrooms",
    options: Array.from({ length: 10 }, (_, i) => i + 1),
    value: "",
  },
  balconies: {
    key: "balconies",
    type: "btnSingle",
    label: "Balconies",
    options: Array.from({ length: 11 }, (_, i) => i),
    value: "",
  },
  floorNo: {
    key: "floorNo",
    type: "select",
    label: "Floor No.",
    options: [
      "Lower",
      "BasementUpper",
      "BasementGround",
      ...Array.from({ length: 200 }, (_, i) => i + 1),
    ],
    value: "",
  },
  totalFloors: {
    key: "totalFloors",
    type: "select",
    label: "Total Floor of the Building",
    options: Array.from({ length: 200 }, (_, i) => i + 1),
    value: "",
  },
  furnishedStatus: {
    key: "furnishedStatus",
    type: "btnSingle",
    label: "Furnished Status",
    options: ["Furnished", "Semi-Furnished", "Unfurnished"],
    value: "",
  },
  floorsAllowed: {
    key: "floorsAllowed",
    type: "select",
    label: "Floors Allowed For Construction",
    options: Array.from({ length: 200 }, (_, i) => i + 1),
    value: "",
  },
  noOfOpenSides: {
    key: "noOfOpenSides",
    type: "btnSingle",
    label: "No Of Open Sides",
    options: [1, 2, 3, 4],
    value: "",
  },
  widthOfRoadFacing: {
    key: "widthOfRoadFacing",
    type: "text",
    label: "Width Of Road Facing The Plot",
    value: "",
  },
  anyConstructionDone: {
    key: "anyConstructionDone",
    type: "radio",
    label: "Any Construction Done",
    options: ["Yes", "No"],
    value: "",
  },
  boundaryWallMade: {
    key: "boundaryWallMade",
    type: "radio",
    label: "Boundary Wall Made",
    options: ["Yes", "No"],
    value: "",
  },
  isInAGatedColony: {
    key: "isInAGatedColony",
    type: "radio",
    label: "Is in a Gated Colony",
    options: ["Yes", "No"],
    value: "",
  },
  washrooms: {
    key: "washrooms",
    type: "btnSingle",
    label: "Washrooms",
    options: Array.from({ length: 10 }, (_, i) => i + 1),
    value: "",
  },
  personalWashroom: {
    key: "personalWashroom",
    type: "radio",
    label: "Personal Washroom",
    options: ["Yes", "No"],
    value: "",
  },
  pantryCafeteria: {
    key: "pantryCafeteria",
    type: "radio",
    label: "Pantry/Cafeteria",
    options: ["Dry", "Wet", "Not Available"],
    value: "",
  },
  willingToModifInteriors: {
    key: "willingToModifInteriors",
    type: "radio",
    label: "Willing to modify interiors",
    options: ["Yes", "No"],
    value: "",
  },
  lockinPeriod: {
    key: "lockinPeriod",
    type: "number",
    label: "Lock-in Period (In Years)",
    value: "",
  },
  cornerShop: {
    key: "cornerShop",
    type: "radio",
    label: "Corner Shop",
    options: ["Yes", "No"],
    value: "",
  },
  isMainRoadFacing: {
    key: "isMainRoadFacing",
    type: "radio",
    label: "Is Main Road Facing",
    options: ["Yes", "No"],
    value: "",
  },
  cornerShowroom: {
    key: "cornerShowroom",
    type: "radio",
    label: "Corner Showroom",
    options: ["Yes", "No"],
    value: "",
  },
  areaIn: {
    key: "areaIn",
    type: "select",
    label: "Area In",
    options: [
      "Sq-ft",
      "Sq-yrd",
      "Sq-m",
      "Acre",
      "Bigha",
      "Hectare",
      "Marla",
      "Kanal",
      "Biswa1",
      "Biswa2",
      "Ground",
      "Aankadam",
      "Rood",
      "Chatak",
      "Kottah",
      "Marla",
      "Cent",
      "Perch",
      "Guntha",
      "Are",
    ],
    value: "",
  },
  superArea: {
    key: "superArea",
    type: "number",
    label: "Super Area",
    value: "",
  },
  builtupArea: {
    key: "builtupArea",
    type: "number",
    label: "Built-up Area",
    value: "",
  },
  carpetArea: {
    key: "carpetArea",
    type: "number",
    label: "Carpet Area",
    value: "",
  },
  coveredArea: {
    key: "coveredArea",
    type: "number",
    label: "Covered Area",
    value: "",
  },
  widthOfEntrance: {
    key: "widthOfEntrance",
    type: "number",
    label: "Width Of Entrance(ft)",
    value: "",
  },
  plotArea: {
    key: "plotArea",
    type: "number",
    label: "Plot Area",
    value: "",
  },
  plotLength: {
    key: "plotLength",
    type: "number",
    label: "Plot Length",
    value: "",
  },
  plotBreadth: {
    key: "plotBreadth",
    type: "number",
    label: "Plot Breadth",
    value: "",
  },
  isCornerPlot: {
    key: "isCornerPlot",
    type: "checkbox",
    label: "",
    options: ["This is a Corner Plot"],
    value: "",
  },
  community: {
    key: "community",
    type: "checkbox",
    label: "Community",
    options: [
      "Hindu",
      "Christian",
      "Muslim",
      "Gujarati",
      "Punjabi",
      "Marwadi",
      "Cosmos",
    ],
    value: "",
  },
  buildingType: {
    key: "buildingType",
    type: "radio",
    label: "Building Type",
    options: ["Standalone", "Complex", "Township"],
    value: "",
  },
  transactionType: {
    key: "transactionType",
    type: "radio",
    label: "Transaction Type",
    options: ["New Property", "Resale"],
    value: "",
  },
  possessionStatus: {
    key: "possessionStatus",
    type: "radio",
    label: "Possession Status",
    options: ["Ready to Move", "Under Construction"],
    value: "",
  },
  availableFrom: {
    key: "availableFrom",
    type: "date",
    hide: true,
    label: "Possesion Date",
    value: "",
  },
  ageOfConstruction: {
    key: "ageOfConstruction",
    type: "select",
    hide: true,
    label: "Age Of Construction",
    options: [
      "New Construction",
      "Less than 5 years",
      "5 to 10 years",
      "10 to 15 years",
      "15 to 20 years",
      "Above 20 years",
    ],
    value: "",
  },
  expectedPrice: {
    key: "expectedPrice",
    type: "number",
    label: "Expected Price",
    value: "",
  },
  priceInWord: {
    key: "priceInWord",
    type: "text",
    label: "Expected Price In Word",
    value: "",
  },
  pricePerSqft: {
    key: "pricePerSqft",
    type: "number",
    label: "Price Per Sq-ft",
    value: "",
  },
  pricePerSqYrd: {
    key: "pricePerSqYrd",
    type: "number",
    label: "Price Per Sq-Yrd",
    value: "",
  },
  otherCharges: {
    key: "otherCharges",
    type: "text",
    label: "Other Charges",
    value: "",
  },
  stampDutyCharges: {
    key: "stampDutyCharges",
    type: "checkbox",
    label: "",
    options: ["Stamp Duty And Registration Charges Excluded"],
    value: "",
  },
  bookingOrTokenAmount: {
    key: "bookingOrTokenAmount",
    type: "text",
    label: "Booking Or Token Amount",
    value: "",
  },
  maintenanceCharge: {
    key: "maintenanceCharge",
    type: "number",
    label: "maintenance Charge",
    value: "",
  },
  maintenancePer: {
    key: "maintenancePer",
    type: "select",
    label: "Maintenance Per",
    options: [
      "Monthly",
      "Quarterly",
      "Yearly",
      "One-Time",
      "Per sq. Unit Monthly",
    ],
    value: "Monthly",
  },
  monthlyRent: {
    key: "monthlyRent",
    type: "number",
    label: "Monthly Rent",
    value: "",
  },
  electricityCharges: {
    key: "electricityCharges",
    type: "checkbox",
    label: "",
    options: ["Electricity And Water Charges Excluded"],
    value: "",
  },
  depositAmount: {
    key: "depositAmount",
    type: "number",
    label: "Deposit Amount",
    value: "",
  },
  youtubeLink: {
    key: "youtubeLink",
    type: "text",
    label: "Youtube Video Link",
    value: "",
  },
  instagramLink: {
    key: "instagramLink",
    type: "text",
    label: "Instagram Reel Link",
    value: "",
  },
  overlooking: {
    key: "overlooking",
    type: "checkbox",
    label: "Overlooking",
    options: ["Garden/Park", "Pool", "Main Road"],
    value: "",
  },
  carParking: {
    key: "carParking",
    type: "radio",
    label: "Car Parking",
    options: ["Covered", "Open", "None"],
    value: "",
  },
  multiUnitAvai: {
    key: "multiUnitAvai",
    type: "radio",
    label: "Multiple Units Available(Jodi Flats)",
    options: ["Yes", "No"],
    value: "",
  },
  availOfWater: {
    key: "availOfWater",
    type: "select",
    label: "Availability Of Water",
    options: [
      "1 Hour Available",
      "2 Hours Available",
      "6 Hours Available",
      "12 Hours Available",
      "24 Hours Available",
    ],
    value: "",
  },
  statusOfElec: {
    key: "statusOfElec",
    type: "select",
    label: "Status Of Electricity",
    options: [
      "No/Rare Powercut",
      "Less Than 2 Hours Powercut",
      "2 To 4 Hours Powercut",
      "4 To 6 Hours Powercut",
      "Over 6 Hours Powercut",
    ],
    value: "",
  },
  ownershipStatus: {
    key: "ownershipStatus",
    type: "select",
    label: "Ownership Status",
    options: [
      "Freehold",
      "Leasehold",
      "Power Of Attorney",
      "Co-operative Society",
    ],
    value: "",
  },
  plotApprovalAuthority: {
    key: "plotApprovalAuthority",
    type: "radio",
    label: "Plot Approval Authority",
    options: ["Yes", "No"],
    value: "",
  },
  approvedBy: {
    key: "approvedBy",
    type: "select",
    label: "Approved by",
    options: [
      "Municipal Corporation of Greater Mumbai",
      "Mumbai Metropolitan Region Development Authority",
      "Developer",
      "Maharashtra Housing and Area Development Authority",
      "Ramanagara–Channapatna Urban Development Authority",
      "RWA/Co-operative Housing Society",
      "City Municipal Corporation",
      "Development Authority",
      "Power Of Attorney",
      "Co-operative Society",
    ],
    hide: true,
    value: "",
  },
  connectivity: {
    key: "connectivity",
    type: "checkbox",
    label: "Connectivity",
    options: ["Railway", "Airport", "Metro", "Road"],
    value: "",
  },
  within2km: {
    key: "within2km",
    type: "checkbox",
    label: "Connectivity Within 2 km",
    options: [
      "School",
      "College",
      "Hospital",
      "Malls",
      "Market",
      "Station",
      "Bank",
      "Bus Stop",
      "Temple",
    ],
    value: "",
  },
  within5km: {
    key: "within5km",
    type: "checkbox",
    label: "Connectivity Within 5 km",
    options: [
      "School",
      "College",
      "Hospital",
      "Malls",
      "Market",
      "Station",
      "Bank",
      "Bus Stop",
      "Temple",
    ],
    value: "",
  },
  within10km: {
    key: "within10km",
    type: "checkbox",
    label: "Connectivity Within 10 km",
    options: [
      "School",
      "College",
      "Hospital",
      "Malls",
      "Market",
      "Station",
      "Bank",
      "Bus Stop",
      "Temple",
    ],
    value: "",
  },
  flooring: {
    key: "flooring",
    type: "radio",
    label: "Flooring",
    options: [
      "Ceramic Tiles",
      "Granite",
      "Marble",
      "Marbonite",
      "Mosaic",
      "Normal Tiles/Kotah Stone",
      "Vitrified",
      "Wooden",
    ],
    value: "",
  },
  amenities: {
    key: "amenities",
    type: "checkbox",
    label: "Amenities",
    options: [
      "Air Conditioned",
      "Banquet Hall",
      "Bar/Lounge",
      "Cafeteria/Food Court",
      "Club House",
      "Concierge Services",
      "Conference Room",
      "DTH Television Facility",
      "Downtown",
      "Fingerprint Access",
      "Fireplace",
      "Full Glass Wall",
      "Golf Course",
      "Gymnasium",
      "Health club with Steam / Jaccuzi",
      "Helipad",
      "Hilltop",
      "House help accommodation",
      "Intercom Facility",
      "Internet/Wi-Fi Connectivity",
      "Island Kitchen Layout",
      "Jogging and Strolling Track",
      "Laundry Service",
      "Lift",
      "Maintenance Staff",
      "Outdoor Tennis Courts",
      "Park",
      "Piped Gas",
      "Power Back Up",
      "Private Garage",
      "Private Terrace/Garden",
      "Private jaccuzi",
      "Private pool",
      "RO Water System",
      "Rain Water Harvesting",
      "Reserved Parking",
      "Sea facing",
      "Security",
      "Service/Goods Lift",
      "Sky Villa",
      "Water Storage",
      "Water Front",
      "Visitor Parking",
      "Skyline View",
      "Smart Home",
      "Swimming Pool",
      "Vaastu Compliant",
      "Waste Disposal",
      "Theme based Architectures",
      "Wrap Around Balcony",
      "Solar Heating",
      "Solar Panel",
      "Garbage Duct",
    ],
    value: "",
  },
  interestingPropertyDetails: {
    key: "interestingPropertyDetails",
    type: "text",
    multiLine: 3,
    label: "Interesting Property Details",
    value: "",
  },
  landmarksAndNeighbourhood: {
    key: "landmarksAndNeighbourhood",
    type: "text",
    multiLine: 3,
    label: "Landmarks & Neighbourhood",
    value: "",
  },
};

const getPropTypes = (type) => {
  const residential = [
    {
      title: "Flat/Apartment",
      value: "1",
      active: false,
      type: "propertyType",
    },
    {
      title: "Residential House",
      value: "2",
      active: false,
      type: "propertyType",
    },
    /* {
      title: "Villa",
      value: "3",
      active: false,
      type: "propertyType",
    },
    {
      title: "Builder Floor Apartment",
      value: "4",
      active: false,
      type: "propertyType",
    },
    {
      title: "Residential Land/Plot",
      value: "5",
      active: false,
      type: "propertyType",
    },
    {
      title: "Penthouse",
      value: "6",
      active: false,
      type: "propertyType",
    },
    {
      title: "Studio Apartment",
      value: "7",
      active: false,
      type: "propertyType",
    },
    {
      title: "Service Apartment",
      value: "8",
      active: false,
      type: "propertyType",
    },
    {
      title: "Farm House",
      value: "19",
      active: false,
      type: "propertyType",
    }, */
  ];
  const commercial = [
    {
      title: "Commercial Office Space",
      value: "9",
      active: false,
      type: "propertyType",
    },
    {
      title: "Commercial Shop",
      value: "11",
      active: false,
      type: "propertyType",
    },
    /* {
      title: "Office in IT Park/SEZ",
      value: "10",
      active: false,
      type: "propertyType",
    },
    {
      title: "Commercial Showroom",
      value: "12",
      active: false,
      type: "propertyType",
    },
    {
      title: "Commercial Land",
      value: "13",
      active: false,
      type: "propertyType",
    },
    {
      title: "Warehouse/Godown",
      value: "14",
      active: false,
      type: "propertyType",
    },
    {
      title: "Industrial Land",
      value: "15",
      active: false,
      type: "propertyType",
    },
    {
      title: "Industrial Shed",
      value: "16",
      active: false,
      type: "propertyType",
    },
    {
      title: "Industrial Building",
      value: "17",
      active: false,
      type: "propertyType",
    }, */
  ];
  const plots = [
    /* {
      title: "Residential Land/Plot",
      value: "5",
      active: false,
      type: "propertyType",
    },
    {
      title: "Commercial Land",
      value: "13",
      active: false,
      type: "propertyType",
    },
    {
      title: "Industrial Land",
      value: "15",
      active: false,
      type: "propertyType",
    },
    {
      title: "Agricultural Land",
      value: "18",
      active: false,
      type: "propertyType",
    }, */
  ];
  if (type === "residential") return residential;
  else if (type === "commercial") return commercial;
  else if (type === "plots-land") return plots;
  else return [];
};

const getBudgetRange = (forr, type) => {
  const budgetRange = {
    residential: {
      buy: [500000, 100000000],
      rent: [5000, 1000000],
    },
    commercial: {
      buy: [500000, 100000000],
      rent: [5000, 1000000],
    },
    "plots-land": {
      buy: [0, 1000000000],
      rent: [0, 1000000],
    },
  };
  return budgetRange[type]
    ? budgetRange[type][forr] || [0, 100000000]
    : [0, 100000000];
};

const getBudgetSteps = (forr, type) => {
  const steps = {
    residential: {
      buy: 500000,
      rent: 2000,
    },
    commercial: {
      buy: 500000,
      rent: 2000,
    },
    "plots-land": {
      buy: 2500000,
      rent: 50000,
    },
  };
  return steps[type] ? steps[type][forr] || 2000 : 2000;
};

const getBudgetDistance = (forr, type) => {
  const budgetDistance = {
    residential: {
      buy: 5000000,
      rent: 50000,
    },
    commercial: {
      buy: 5000000,
      rent: 50000,
    },
    "plots-land": {
      buy: 50000000,
      rent: 50000,
    },
  };
  return budgetDistance[type] ? budgetDistance[type][forr] || 5000000 : 5000000;
};

const getAreaRange = (forr) => {
  const areaRange = {
    buy: [0, 4000],
    rent: [0, 10000],
  };

  return areaRange[forr] || [0, 10000];
};

const getFilterData = (forr, type) => {
  return [
    {
      key: "propertyType",
      title: "Property Type",
      items: getPropTypes(type),
    },
    {
      key: "bedRoom",
      title: "No. of Bedrooms",
      items: [
        { title: "1 RK/1 BHK", value: "1", active: false, type: "bedRoom" },
        { title: "2 BHK", value: "2", active: false, type: "bedRoom" },
        { title: "3 BHK", value: "3", active: false, type: "bedRoom" },
        { title: "4 BHK", value: "4", active: false, type: "bedRoom" },
        { title: "5 BHK", value: "5", active: false, type: "bedRoom" },
        { title: "6 BHK", value: "6", active: false, type: "bedRoom" },
        { title: "7 BHK", value: "7", active: false, type: "bedRoom" },
        { title: "7+ BHK", value: "7+", active: false, type: "bedRoom" },
      ],
    },
    {
      key: "constructionStatus",
      title: "Construction Status",
      items: [
        {
          title: "Ready To Move",
          value: "1",
          active: false,
          type: "constructionStatus",
        },
        {
          title: "Under Construction",
          value: "2",
          active: false,
          type: "constructionStatus",
        },
      ],
    },
    /* {
      key: "postBy",
      title: "Post By",
      items: [
        { title: "Owner", value: "1", active: false, type: "postBy" },
        { title: "Builder", value: "2", active: false, type: "postBy" },
        { title: "Dealer", value: "3", active: false, type: "postBy" },
      ],
    }, */
    {
      key: "furnishing",
      title: "Furnishing status",
      items: [
        {
          title: "Furnished",
          value: "1",
          active: false,
          type: "furnishing",
        },
        {
          title: "Semifurnished",
          value: "2",
          active: false,
          type: "furnishing",
        },
        {
          title: "Unfurnished",
          value: "3",
          active: false,
          type: "furnishing",
        },
      ],
    },
    {
      key: "area",
      title: "Area",
      range: getAreaRange(forr),
      steps: 200,
      distance: 500,
    },
    {
      key: "budget",
      title: "Budget",
      range: getBudgetRange(forr, type),
      steps: getBudgetSteps(forr, type),
      distance: getBudgetDistance(forr, type),
    },
  ];
};

const getFilterFields = (forr, type) => {
  const fields = {
    residential: {
      sale: [
        "propertyType",
        "bedRoom",
        "constructionStatus",
        // "postBy",
        "budget",
      ],
      rent: [
        "propertyType",
        "bedRoom",
        "furnishing",
        // "postBy",
        "budget",
      ],
    },
    commercial: {
      sale: [
        "propertyType",
        "area",
        "constructionStatus",
        // "postBy",
        "budget",
      ],
      rent: [
        "propertyType",
        "area",
        "constructionStatus",
        // "postBy",
        "budget",
      ],
    },
    "plots-land": {
      sale: [
        "propertyType",
        "area",
        // "postBy",
        "budget",
      ],
      rent: [
        "propertyType",
        "area",
        // "postBy",
        "budget",
      ],
    },
  };

  return fields[type] ? fields[type][forr] || [] : [];
};

const getRequirmentFilterData = (forr, type) => {
  return [
    {
      key: "propertyType",
      title: "Property Type",
      items: getPropTypes(type),
    },
    {
      key: "bedRoom",
      title: "No. of Bedrooms",
      items: [
        { title: "1 RK/1 BHK", value: "1", active: false, type: "bedRoom" },
        { title: "2 BHK", value: "2", active: false, type: "bedRoom" },
        { title: "3 BHK", value: "3", active: false, type: "bedRoom" },
        { title: "4 BHK", value: "4", active: false, type: "bedRoom" },
        { title: "5 BHK", value: "5", active: false, type: "bedRoom" },
        { title: "6 BHK", value: "6", active: false, type: "bedRoom" },
        { title: "7 BHK", value: "7", active: false, type: "bedRoom" },
        { title: "7+ BHK", value: "7+", active: false, type: "bedRoom" },
      ],
    },
    {
      key: "lookingFor",
      title: "Looking For",
      items: [
        {
          title: "Ready Possession",
          value: "1",
          active: false,
          type: "lookingFor",
        },
        {
          title: "Possession in 1 Year",
          value: "2",
          active: false,
          type: "lookingFor",
        },
        {
          title: "Possession in 2 Years",
          value: "3",
          active: false,
          type: "lookingFor",
        },
        {
          title: "Possession in 3 Years",
          value: "4",
          active: false,
          type: "lookingFor",
        },
      ],
    },
    {
      key: "furnishing",
      title: "Furnishing status",
      items: [
        {
          title: "Furnished",
          value: "1",
          active: false,
          type: "furnishing",
        },
        {
          title: "Semifurnished",
          value: "2",
          active: false,
          type: "furnishing",
        },
        {
          title: "Unfurnished",
          value: "3",
          active: false,
          type: "furnishing",
        },
      ],
    },
    {
      key: "budget",
      title: "Budget",
      range: getBudgetRange(forr, type),
      steps: getBudgetSteps(forr, type),
      distance: getBudgetDistance(forr, type),
    },
  ];
};

const hideRequirementFields = {
  bedrooms: [
    "Residential Land/Plot",
    "Commercial Office Space",
    "Office in IT Park/SEZ",
    "Commercial Shop",
    "Commercial Showroom",
    "Commercial Land",
    "Warehouse/Godown",
    "Industrial Land",
    "Industrial Building",
    "Industrial Shed",
    "Agricultural Land",
  ],
  lookingFor: [
    "Residential Land/Plot",
    "Commercial Land",
    "Industrial Land",
    "Agricultural Land",
    "Farm House",
  ],
  floor: [
    "Residential House",
    "Villa",
    "Residential Land/Plot",
    "Commercial Land",
    "Warehouse/Godown",
    "Industrial Land",
    "Industrial Shed",
    "Agricultural Land",
    "Farm House",
  ],
  parking: [
    "Residential Land/Plot",
    "Commercial Land",
    "Industrial Land",
    "Industrial Shed",
    "Agricultural Land",
  ],
  balcony: [
    "Residential Land/Plot",
    "Commercial Office Space",
    "Office in IT Park/SEZ",
    "Commercial Shop",
    "Commercial Showroom",
    "Commercial Land",
    "Warehouse/Godown",
    "Industrial Land",
    "Industrial Building",
    "Industrial Shed",
    "Agricultural Land",
  ],
  furnish_status: [
    "Residential Land/Plot",
    "Commercial Land",
    "Warehouse/Godown",
    "Industrial Land",
    "Industrial Shed",
    "Agricultural Land",
  ],
  community: [
    "Residential Land/Plot",
    "Commercial Land",
    "Industrial Land",
    "Industrial Shed",
    "Agricultural Land",
    "Farm House",
  ],
  buildingType: [
    "Residential House",
    "Villa",
    "Residential Land/Plot",
    "Commercial Land",
    "Warehouse/Godown",
    "Industrial Land",
    "Industrial Shed",
    "Agricultural Land",
    "Farm House",
  ],
};

const sortList = [
  { title: "Relevance", value: "rlv" },
  { title: "Newest first", value: "nf" },
  { title: "Price Low to High", value: "lth" },
  { title: "Price High to Low", value: "htl" },
  // { title: "Price / sq.ft. : Low to High", value: "" },
  // { title: "Price / sq.ft. : High to Low", value: "" },
];

module.exports = {
  keyMap,
  keyValues,
  imageTypes,
  propertyCardFields,
  step1FormFields,
  requirementFormData,
  propertyFormData,
  getFilterData,
  getFilterFields,
  getRequirmentFilterData,
  hideRequirementFields,
  sortList,
};
